"""init

Revision ID: ee8f6ff11981
Revises: 
Create Date: 2026-02-24 00:35:23.529352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee8f6ff11981'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trabajos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('tarea_numero', sa.String(length=50), nullable=False),
    sa.Column('cliente_nombre', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('categoria', sa.String(length=200), nullable=True),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_finalizada', sa.Time(), nullable=True),
    sa.Column('empleado_objetivo', sa.String(length=200), nullable=False),
    sa.Column('fuente_archivo_nombre', sa.String(length=500), nullable=False),
    sa.Column('fuente_archivo_tipo', sa.String(length=50), nullable=False),
    sa.Column('fuente_archivo_hash', sa.String(length=64), nullable=False),
    sa.Column('incompleto', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dedup', 'trabajos', ['fuente_archivo_hash', 'tarea_numero', 'fecha_inicio', 'empleado_objetivo'], unique=True)
    op.create_index(op.f('ix_trabajos_cliente_nombre'), 'trabajos', ['cliente_nombre'], unique=False)
    op.create_index(op.f('ix_trabajos_estado'), 'trabajos', ['estado'], unique=False)
    op.create_index(op.f('ix_trabajos_fecha_inicio'), 'trabajos', ['fecha_inicio'], unique=False)
    op.create_index(op.f('ix_trabajos_tarea_numero'), 'trabajos', ['tarea_numero'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trabajos_tarea_numero'), table_name='trabajos')
    op.drop_index(op.f('ix_trabajos_fecha_inicio'), table_name='trabajos')
    op.drop_index(op.f('ix_trabajos_estado'), table_name='trabajos')
    op.drop_index(op.f('ix_trabajos_cliente_nombre'), table_name='trabajos')
    op.drop_index('idx_dedup', table_name='trabajos')
    op.drop_table('trabajos')
    # ### end Alembic commands ###
